#!/usr/bin/env bash
#!/bin/bash
# Script to display information about a domain and its subdomains

subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
subdomain="$2"

dig_ip_config() {
	# func variables
	subdomain="$2"
	INFO="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $subdomain is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
	for subs in "${subdomains[@]}"; do
		dig_cmd "$domain" "$subs"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$domain" "$subdomain"
fi
