#!/usr/bin/env bash
# Declare variables and parameters
subdomains=( "www" "lb-01" "web-01" "web-02" )
maindomain="$1"
subdomain="$2"

# Function to retrieve and display DNS information for a subdomain
dig_cmd () {
        # Get DNS information for the specified subdomain
        sub="$2"
        INFO="$(dig "$sub.$maindomain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
        IP=$(echo "$INFO" | awk '{print $5}')
        RECORD=$(echo "$INFO" | awk '{print $4}')

        # Display the DNS information for the specified subdomain
        echo "The subdomain $sub is a $RECORD record and points to $IP"
}

# Check the number of arguments passed to the script
if [ $# -eq 1 ]; then
        # If only the domain name is provided, display DNS information for all subdomains
        for subs in "${subdomains[@]}"; do
                dig_cmd "$maindomain" "$subs"
        done
elif [ $# -eq 2 ]; then
        # If a specific subdomain is provided, display DNS information for that subdomain only
        dig_cmd "$maindomain" "$subdomain"
fi

