#!/bin/bash



path=$(realpath “${BASH_SOURCE:-$0}”)

echo ‘The absolute path is’ $path



echo ‘-----------------------------------’



DIR_PATH=$(dirname $path)

echo ‘The directory path is’ $DPATH
