#!/usr/bin/env bash
#Making it shorter
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'

